// Person.c - Generated by GSL for entity Person

#include "Person.h"
#include <string.h>
// --- Function to create a new PersonNode ---
PersonNode* createPersonNode(
  int id,
  const char* firstname,
  const char* lastname,
  int age
) {
  PersonNode* newNode = (PersonNode*)malloc(sizeof(PersonNode));
  if (newNode == NULL)  goto Person_cleanup;

  // Initialize data fields
  newNode->data.id = id;
  newNode->data.firstname = strdup(firstname);
  if (newNode->data.firstname == NULL && firstname != NULL) goto Person_cleanup;
  newNode->data.lastname = strdup(lastname);
  if (newNode->data.lastname == NULL && lastname != NULL) goto Person_cleanup;
  newNode->data.age = age;

  newNode->next = NULL;
  return newNode;

Person_cleanup:
  // Initialize data fields
  free(newNode->data.firstname);
  free(newNode->data.lastname);
  free(newNode);
  return NULL;
}

// --- Function to add a PersonNode to the end of the list ---
void addPersonToList(PersonNode** head, PersonNode* newNode) {
  if (newNode == NULL) return;
  if (*head == NULL) {
    *head = newNode;
  } else {
    PersonNode* current = *head;
    while (current->next != NULL) {
      current = current->next;
    }
    current->next = newNode;
  }
}

// --- Function to print details of a single Person ---
void printPerson(const Person* entityData) {
    if (entityData == NULL) {
      printf("  (null Person data)\n");
      return;
    }
    printf("  Person Details:\n");
    printf("    id: %d\n", entityData->id);
    printf("    firstname: %s\n", entityData->firstname ? entityData->firstname : "(null)");
    printf("    lastname: %s\n", entityData->lastname ? entityData->lastname : "(null)");
    printf("    age: %d\n", entityData->age);
}

// --- Function to print all Persons in the list ---
void printPersonList(const PersonNode* head) {
  const PersonNode* current = head;
  if (current == NULL) {
    printf("Person list is empty.\n");
    return;
  }
  printf("\n--- Person List ---\n");
  int count = 1;
  while (current != NULL) {
    printf("Node %d:\n", count++);
    printPerson(&(current->data));
    current = current->next;
  }
  printf("----------------------\n");
}

// --- Function to free the entire Person linked list ---
void freePersonList(PersonNode** head) {
  PersonNode* current = *head;
  PersonNode* nextNode;
  while (current != NULL) {
    nextNode = current->next;
    // Free dynamically allocated strings within the data struct
    free(current->data.firstname);
    free(current->data.lastname);
    free(current); // Free the node itself
    current = nextNode;
  }
  *head = NULL;
}
