// Product.h - Generated by GSL for entity Product

#ifndef PRODUCT_H
#define PRODUCT_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// --- Definition for Product struct ---
typedef struct Product {
  char* sku; // Stock Keeping Unit;
  char* name; // Name of the product;
  double price; // Price of the product;
  int quantity; // Available quantity in stock;
} Product;

// --- Definition for ProductNode (Linked List Node) ---
typedef struct ProductNode {
  Product data; // Embeds the actual entity data
  struct ProductNode *next;
} ProductNode;

// --- Function Prototypes for Product Linked List ---
ProductNode* createProductNode(
  const char* sku,
  const char* name,
  double price,
  int quantity
);

void addProductToList(ProductNode** head, ProductNode* newNode);
void printProduct(const Product* entityData);
void printProductList(const ProductNode* head);
void freeProductList(ProductNode** head);

#endif // PRODUCT_H
