// Product.c - Generated by GSL for entity Product

#include "Product.h"
#include <string.h>
// --- Function to create a new ProductNode ---
ProductNode* createProductNode(
  const char* sku,
  const char* name,
  double price,
  int quantity
) {
  ProductNode* newNode = (ProductNode*)malloc(sizeof(ProductNode));
  if (newNode == NULL)  goto Product_cleanup;

  // Initialize data fields
  newNode->data.sku = strdup(sku);
  if (newNode->data.sku == NULL && sku != NULL) goto Product_cleanup;
  newNode->data.name = strdup(name);
  if (newNode->data.name == NULL && name != NULL) goto Product_cleanup;
  newNode->data.price = price;
  newNode->data.quantity = quantity;

  newNode->next = NULL;
  return newNode;

Product_cleanup:
  // Initialize data fields
  free(newNode->data.sku);
  free(newNode->data.name);
  free(newNode);
  return NULL;
}

// --- Function to add a ProductNode to the end of the list ---
void addProductToList(ProductNode** head, ProductNode* newNode) {
  if (newNode == NULL) return;
  if (*head == NULL) {
    *head = newNode;
  } else {
    ProductNode* current = *head;
    while (current->next != NULL) {
      current = current->next;
    }
    current->next = newNode;
  }
}

// --- Function to print details of a single Product ---
void printProduct(const Product* entityData) {
    if (entityData == NULL) {
      printf("  (null Product data)\n");
      return;
    }
    printf("  Product Details:\n");
    printf("    sku: %s\n", entityData->sku ? entityData->sku : "(null)");
    printf("    name: %s\n", entityData->name ? entityData->name : "(null)");
    printf("    price: %.2f\n", entityData->price);
    printf("    quantity: %d\n", entityData->quantity);
}

// --- Function to print all Products in the list ---
void printProductList(const ProductNode* head) {
  const ProductNode* current = head;
  if (current == NULL) {
    printf("Product list is empty.\n");
    return;
  }
  printf("\n--- Product List ---\n");
  int count = 1;
  while (current != NULL) {
    printf("Node %d:\n", count++);
    printProduct(&(current->data));
    current = current->next;
  }
  printf("----------------------\n");
}

// --- Function to free the entire Product linked list ---
void freeProductList(ProductNode** head) {
  ProductNode* current = *head;
  ProductNode* nextNode;
  while (current != NULL) {
    nextNode = current->next;
    // Free dynamically allocated strings within the data struct
    free(current->data.sku);
    free(current->data.name);
    free(current); // Free the node itself
    current = nextNode;
  }
  *head = NULL;
}
